### ISSUE TITLE
[OTHER] Add steps to re-produce issues to the GH issue form

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#706]
### What would you like to share?

Currently, there's no explicit field the prompts contributors to list steps to reproduce bugs they're raising issues for. I believe adding this field could be useful for debugging purposes.

### Additional information

If this is implemented, it'll also be helpful to add it to the contributing guidelines doc

### What to do?
add this line of code after this -> https://github.com/Dun-sin/Whisper/blob/7a65dac0a3b0af47ef76b3414f1e91f1a08d2c0b/.github/ISSUE_TEMPLATE/bug.yml?plain=1#L27

```
 type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: What do we have to do to reproduce/experience this bug
    validations:
      required: true
```
